{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12402891","self":"https://issues.apache.org/jira/rest/api/2/issue/12402891","key":"OPENJPA-699","fields":{"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313624","id":"12313624","description":"OpenJPA 2.0.0 Milestone 1","name":"2.0.0-M1","archived":false,"released":true,"releaseDate":"2009-01-29"}],"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12312323":null,"customfield_12312320":null,"customfield_12310420":"161011","customfield_12312321":null,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12312331":null,"customfield_12312332":null,"aggregatetimeoriginalestimate":null,"timeestimate":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312341","id":"12312341","description":"","name":"1.0.0","archived":false,"released":true,"releaseDate":"2007-08-28"}],"customfield_12311120":null,"customfield_12313826":null,"customfield_12312339":null,"issuelinks":[],"customfield_12313825":null,"assignee":null,"customfield_12312337":null,"customfield_12313823":null,"customfield_12312338":null,"customfield_12311920":null,"customfield_12313822":null,"customfield_12312335":null,"customfield_12313821":null,"customfield_12312336":null,"customfield_12313820":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12311307","id":"12311307","name":"diagnostics","description":"Issues related to error messages, warnings, and other diagnostic information."}],"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"202674","customfield_12312823":null,"creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"subtasks":[],"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"aggregateprogress":{"progress":0,"total":0},"customfield_12313520":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"customfield_12313924":null,"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/OPENJPA-699/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12313920":null,"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"customfield_12314020":"{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@1f632a05[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@1cac1e5d[overall=PullRequestOverallBean{stateCount=0, state='OPEN', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@62a7ee97[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@1e855a68[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@9fe9647[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@7b864e29[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@2688c498[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@126a9c3b[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@6f5b7c9f[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@26e5805b[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@46a92c1b[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@64fbb1[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={\"cachedValue\":{\"errors\":[],\"configErrors\":[],\"summary\":{\"pullrequest\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":\"OPEN\",\"details\":{\"openCount\":0,\"mergedCount\":0,\"declinedCount\":0,\"total\":0},\"open\":true},\"byInstanceType\":{}},\"build\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"failedBuildCount\":0,\"successfulBuildCount\":0,\"unknownBuildCount\":0},\"byInstanceType\":{}},\"review\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":null,\"dueDate\":null,\"overDue\":false,\"completed\":false},\"byInstanceType\":{}},\"deployment-environment\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"topEnvironments\":[],\"showProjects\":false,\"successfulCount\":0},\"byInstanceType\":{}},\"repository\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}},\"branch\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}}}},\"isStale\":false}}","customfield_12314141":null,"customfield_12314140":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310351","id":"12310351","key":"OPENJPA","name":"OpenJPA","projectTypeKey":"software","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310351&avatarId=10043","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310351&avatarId=10043","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310351&avatarId=10043","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310351&avatarId=10043"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10252","id":"10252","description":"","name":"OpenJPA"}},"aggregatetimespent":null,"customfield_12312520":null,"customfield_12314422":null,"customfield_12314421":null,"customfield_12314146":null,"customfield_12314420":null,"customfield_12314145":null,"customfield_12314144":null,"customfield_12314143":null,"resolutiondate":"2008-08-27T16:47:11.149+0000","workratio":-1,"customfield_12312923":null,"customfield_12312920":null,"customfield_12312921":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/OPENJPA-699/watchers","watchCount":1,"isWatching":false},"created":"2008-08-22T17:24:33.450+0000","updated":"2010-03-09T18:31:01.816+0000","timeoriginalestimate":null,"description":"If set  \"kodo.ConnectionFactoryProperties\" \"warningAction\" to \"throw\" or \"handle\", when an INSERT statement fails due \nto an attempt to insert null into a non-null column, log output is  \"The statement has been \nterminated\".\nIf didn't set  \"warningAction\", the default value is \"ignore\". It logs correct SQLException which is as follows:\n\nCannot \ninsert the value NULL into column 'TestTimeNotNullNoDefaultUtc', table \n'STADatabase.dbo.DefaultValuesJ'; column does not allow nulls. INSERT fails. \n{prepstmnt 112461492 \n... ...\n\nIn org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator.LoggingPreparedStatement.executeUpdate(), the \ncode is\n            public int executeUpdate(String sql) throws SQLException {\n                _sql = sql;\n                logSQL(this);\n                long start = System.currentTimeMillis();\n                try {\n                    return super.executeUpdate(sql);\n                } catch (SQLException se) {\n                    throw wrap(se, LoggingStatement.this);\n                } finally {\n                    logTime(start);\n                    handleSQLWarning(LoggingStatement.this);\n                }\n            }\nIn this test case, it got a SQLWarning with msg 'The statement has been \nterminated' and a SQLException which tells Column null is not allowed.\nWhen WarningAction is set to 'throw' or 'handle' and if handle doesn't \nconsume the warning but throw it, the SQLWarning is thrown from finally \nblock.\nThe SQLWarning which it is a subclass of SQLException will be processed by \nDBdictionary.newStoreException() so we see the incorrect message.\n\n","customfield_10010":null,"timetracking":{},"customfield_12314523":null,"customfield_12314127":null,"customfield_12314522":null,"customfield_12314126":null,"customfield_12314521":null,"customfield_12314125":null,"customfield_12314520":null,"customfield_12314124":null,"attachment":[{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12388776","id":"12388776","filename":"openJPA-699.patch","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-22T21:30:59.887+0000","size":9000,"mimeType":"text/x-patch","content":"https://issues.apache.org/jira/secure/attachment/12388776/openJPA-699.patch"},{"self":"https://issues.apache.org/jira/rest/api/2/attachment/12388928","id":"12388928","filename":"openJPA-699-v2.patch","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-26T17:40:58.398+0000","size":32073,"mimeType":"text/x-patch","content":"https://issues.apache.org/jira/secure/attachment/12388928/openJPA-699-v2.patch"}],"customfield_12312340":null,"customfield_12314123":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12314122":null,"customfield_12314121":null,"customfield_12310041":null,"customfield_12314120":null,"customfield_12314129":null,"customfield_12314524":null,"customfield_12314128":null,"summary":"SQLWarnings not handled properly with WarningAction set to \"handle\"","customfield_12314130":null,"customfield_12310291":null,"customfield_12310290":null,"customfield_12314138":null,"customfield_12314137":null,"environment":"Kodo 4.1.4\nOpenJPA 1.0.0\nMS SQL 2005\nMS JDBC DRIVER VERSION  1.1 \nJDK 1.5","customfield_12314136":null,"customfield_12314135":null,"customfield_12311020":null,"customfield_12314134":null,"duedate":null,"customfield_12314132":null,"customfield_12314131":null,"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12624983","id":"12624983","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"body":"This is the proposed patch. \nProposed solution is when a SQLException is catched and WarningAction is set to 'throw' or 'handle', we skip handleSQLwarning.\n\nSolution is tested on customer case.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-22T21:30:59.908+0000","updated":"2008-08-22T21:30:59.908+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12625423","id":"12625423","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=awhite","name":"awhite","key":"awhite","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"A. Abram White","active":true,"timeZone":"Etc/UTC"},"body":"Why don't we just always skip SQL warnings when we're throwing an exception?  I.e. just move all handleSQLWarning(...) calls to within the try{ ... } after calling super(...) rather than in the finally block?  It seems that when there is a thrown exception, warnings will always be either extraneous or completely meaningless as in this bug report.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=awhite","name":"awhite","key":"awhite","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"A. Abram White","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-25T16:38:59.699+0000","updated":"2008-08-25T16:38:59.699+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12625431","id":"12625431","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"body":"I was thinking to add fix with least change of existing behavior. So customer can still get log message of warning with other warning action property when exception is thrown. \nI agree that usually when exception is thrown, warnings are meaningless.\nI am fine with move handleSQLWarning() call to try block.\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-25T17:30:19.072+0000","updated":"2008-08-25T17:30:19.072+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12625433","id":"12625433","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=joe+weinstein","name":"joe weinstein","key":"joe weinstein","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Joe Weinstein","active":true,"timeZone":"Etc/UTC"},"body":"Hi. Actually sometimes the DBMS and driver implement it so the one SQLException\nis fairly generic, with a lot of detail relegated to the messages in the SQLWarnings.\nI have even seen SQLExceptions which state \"Please see the information in the\nchained SQLWarnings\"!\nJoe Weinstein","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=joe+weinstein","name":"joe weinstein","key":"joe weinstein","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Joe Weinstein","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-25T17:40:31.516+0000","updated":"2008-08-25T17:40:31.516+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12625452","id":"12625452","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=awhite","name":"awhite","key":"awhite","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"A. Abram White","active":true,"timeZone":"Etc/UTC"},"body":"If Joe is right then neither my proposed solution nor the attached patch are acceptable.  We need to capture the output of both the exception and any warnings.  So I propose the following changes to LoggingConnectionDecorator:\n\n1. Change the following pattern: \ntry {...} catch(SQLException se) { throw wrap(se...); } finally { ... handleSQLWarnings(...); }\nto:\nSQLException err = null;\ntry {...} catch(SQLException se) { err = wrap(se...); } finally { ... handleSQLErrors(..., err); }\n\n2. Change all the handleSQLWarnings methods except handleSQLWarnings(SQLWarning) to be named handleSQLErrors and to accept an extra SQLException argument.  The try/finally blocks in these methods will become try/catch/finally blocks where the catch captures the thrown exception.  At the end of the method we combine the passed-in exception with the thrown exception and throw the result as a single exception (unless either/both are null of course, in which case we throw the non-null one or nothing at all).  \n\n3. Fix all the prepareStatement/createStatement methods that currently don't have handleSQLWarnings in a finally block at all to use a try/catch/finally block as outlined in change #1 above.\n\nDoes that sound acceptable?  We might still get extraneous \"The statement has been closed\" output in the combined exceptions we throw under certain drivers, but at least no information will get lost.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=awhite","name":"awhite","key":"awhite","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"A. Abram White","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-25T18:33:28.531+0000","updated":"2008-08-25T18:33:28.531+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12625466","id":"12625466","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"body":"That is a good plan.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-25T19:07:04.201+0000","updated":"2008-08-25T19:07:04.201+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12625802","id":"12625802","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"body":"Here is the revised patch according to our discussion.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=xiaoqinfeng2000","name":"xiaoqinfeng2000","key":"xiaoqinfeng2000","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Xiaoqin Feng","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-26T17:40:58.445+0000","updated":"2008-08-26T17:40:58.445+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12402891/comment/12626180","id":"12626180","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=awhite","name":"awhite","key":"awhite","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"A. Abram White","active":true,"timeZone":"Etc/UTC"},"body":"Applied v2 patch per comments in SVN revision 689518.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=awhite","name":"awhite","key":"awhite","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"A. Abram White","active":true,"timeZone":"Etc/UTC"},"created":"2008-08-27T16:47:11.080+0000","updated":"2008-08-27T16:47:11.080+0000"}],"maxResults":8,"total":8,"startAt":0},"customfield_12311820":"0|i0z2an:","customfield_12314139":null}}

