{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"12383824","self":"https://issues.apache.org/jira/rest/api/2/issue/12383824","key":"OPENJPA-458","fields":{"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313102","id":"12313102","description":"","name":"1.2.0","archived":false,"released":true,"releaseDate":"2008-08-12"}],"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12312322":null,"customfield_12312323":null,"customfield_12312320":null,"customfield_12310420":"160779","customfield_12312321":null,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312720":null,"customfield_12312325":null,"lastViewed":null,"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/2","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/critical.svg","name":"Critical","id":"2"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12313422":"false","customfield_12312331":null,"customfield_12312332":null,"aggregatetimeoriginalestimate":null,"timeestimate":null,"customfield_12312330":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312687","id":"12312687","description":"","name":"1.0.1","archived":false,"released":true,"releaseDate":"2007-11-09"}],"customfield_12311120":null,"customfield_12313826":null,"customfield_12312339":null,"issuelinks":[{"id":"12320671","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12320671","type":{"id":"12310010","name":"Incorporates","inward":"is part of","outward":"incorporates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310010"},"outwardIssue":{"id":"12384082","key":"OPENJPA-462","self":"https://issues.apache.org/jira/rest/api/2/issue/12384082","fields":{"summary":"OptimisticException is thrown instead of OptimisticLockException","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.svg","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133}}}}],"customfield_12313825":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=ppoddar%40apache.org","name":"ppoddar@apache.org","key":"ppoddar@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Pinaki Poddar","active":true,"timeZone":"America/Los_Angeles"},"customfield_12312337":null,"customfield_12313823":null,"customfield_12312338":null,"customfield_12311920":null,"customfield_12313822":null,"customfield_12312335":null,"customfield_12313821":null,"customfield_12312336":null,"customfield_12313820":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12311304","id":"12311304","name":"jpa","description":"Java Persistence API interface"}],"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12310921":null,"customfield_12310920":"201663","customfield_12312823":null,"creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=onural%40nortel.com","name":"onural@nortel.com","key":"onural@nortel.com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gul Onural","active":true,"timeZone":"Etc/UTC"},"subtasks":[],"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=onural%40nortel.com","name":"onural@nortel.com","key":"onural@nortel.com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Gul Onural","active":true,"timeZone":"Etc/UTC"},"aggregateprogress":{"progress":0,"total":0},"customfield_12313520":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"customfield_12313924":null,"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/OPENJPA-458/votes","votes":1,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12313920":null,"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/secure/viewavatar?size=xsmall&avatarId=21133&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":21133},"timespent":null,"customfield_12314020":"{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@77f1b867[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@593b85e8[overall=PullRequestOverallBean{stateCount=0, state='OPEN', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@315e81fd[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@34cf46fb[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@7a8aa464[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@358427[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@4521bcb5[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@b97d274[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@2491fee6[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@82942ef[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@40a5934b[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@7514ed59[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={\"cachedValue\":{\"errors\":[],\"configErrors\":[],\"summary\":{\"pullrequest\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":\"OPEN\",\"details\":{\"openCount\":0,\"mergedCount\":0,\"declinedCount\":0,\"total\":0},\"open\":true},\"byInstanceType\":{}},\"build\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"failedBuildCount\":0,\"successfulBuildCount\":0,\"unknownBuildCount\":0},\"byInstanceType\":{}},\"review\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":null,\"dueDate\":null,\"overDue\":false,\"completed\":false},\"byInstanceType\":{}},\"deployment-environment\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"topEnvironments\":[],\"showProjects\":false,\"successfulCount\":0},\"byInstanceType\":{}},\"repository\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}},\"branch\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}}}},\"isStale\":false}}","customfield_12314141":null,"customfield_12314140":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310351","id":"12310351","key":"OPENJPA","name":"OpenJPA","projectTypeKey":"software","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310351&avatarId=10043","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310351&avatarId=10043","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310351&avatarId=10043","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310351&avatarId=10043"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10252","id":"10252","description":"","name":"OpenJPA"}},"aggregatetimespent":null,"customfield_12312520":null,"customfield_12314422":null,"customfield_12314421":null,"customfield_12314146":null,"customfield_12314420":null,"customfield_12314145":null,"customfield_12314144":null,"customfield_12314143":null,"resolutiondate":"2008-07-16T02:37:09.688+0000","workratio":-1,"customfield_12312923":null,"customfield_12312920":null,"customfield_12312921":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/OPENJPA-458/watchers","watchCount":1,"isWatching":false},"created":"2007-12-03T21:47:17.873+0000","updated":"2010-03-09T18:32:42.521+0000","timeoriginalestimate":null,"description":"OpenJPA doesn't throw standard JPA exceptions in the case of failure to persist or commit. \n\nFor example, the JPA spec states that the EntityExistsException is thrown by the persistence provider when EntityManager.persist(Object) is called and the entity already exists. \n\nHowever, the OpenJPA never raises the EntityExistsException, instead raises RollbackException.\n\nIn order to produce the issue, just take the hellojpa example comes with the OpenJPA distro. and modify Message.java to make \nvariable message an ID (original Message class uses timestamp as ID, just change the ID to be message variable for the purpose of  reproducing the issue explained here) : \n   @Id\n    private String message;\n\nThen run the hellojpa after this very simple modification, twice. Second execution fails because of duplicate key. The stack trace is captured below and notice that there is no  EntityExistsException in the stack trace at all. \n\nBecause of this, the caller of the jpa objects cannot differenciate EntityExistsException from any other exception and for example the GUI cleints cannot display meaningful error code to reflect exactly what happend. \n\nHere is the stack trace :\n\nBuildfile: D:\\apache-openjpa-1.0.0\\examples\\hellojpa\\build.xml\npre-compile:\ncompile:\nrun:\n     [java] 3063  hellojpa  TRACE  [main] openjpa.jdbc.SQL - <t 26760685, conn 3238031> executing prepstmnt 28409161 INSERT INTO Message (message, created, id) VALUES (?, ?, ?) [params=(String) Hello Persistence!, (Timestamp) 2007-12-03 15:59:24.663, (long) 1196715564663]\n     [java] 3157  hellojpa  TRACE  [main] openjpa.jdbc.SQL - <t 26760685, conn 3238031> [94 ms] spent\n     [java] Exception in thread \"main\" <openjpa-1.0.0-r420667:568756 fatal store error> org.apache.openjpa.persistence.RollbackException: The transaction has been rolled back.  See the nested exceptions for details on the errors that occurred.\n     [java] \tat org.apache.openjpa.persistence.EntityManagerImpl.commit(EntityManagerImpl.java:419)\n     [java] \tat hellojpa.Main.main(Main.java:53)\n     [java] Caused by: <openjpa-1.0.0-r420667:568756 fatal general error> org.apache.openjpa.persistence.PersistenceException: The transaction has been rolled back.  See the nested exceptions for details on the errors that occurred.\n     [java] \tat org.apache.openjpa.kernel.BrokerImpl.newFlushException(BrokerImpl.java:2099)\n     [java] \tat org.apache.openjpa.kernel.BrokerImpl.flush(BrokerImpl.java:1946)\n     [java] \tat org.apache.openjpa.kernel.BrokerImpl.flushSafe(BrokerImpl.java:1844)\n     [java] \tat org.apache.openjpa.kernel.BrokerImpl.beforeCompletion(BrokerImpl.java:1762)\n     [java] \tat org.apache.openjpa.kernel.LocalManagedRuntime.commit(LocalManagedRuntime.java:81)\n     [java] \tat org.apache.openjpa.kernel.BrokerImpl.commit(BrokerImpl.java:1292)\n     [java] \tat org.apache.openjpa.kernel.DelegatingBroker.commit(DelegatingBroker.java:861)\n     [java] \tat org.apache.openjpa.persistence.EntityManagerImpl.commit(EntityManagerImpl.java:408)\n     [java] \t... 1 more\n     [java] Caused by: <openjpa-1.0.0-r420667:568756 nonfatal general error> org.apache.openjpa.persistence.PersistenceException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL071203035857400' defined on 'MESSAGE'. {prepstmnt 28409161 INSERT INTO Message (message, created, id) VALUES (?, ?, ?) [params=(String) Hello Persistence!, (Timestamp) 2007-12-03 15:59:24.663, (long) 1196715564663]} [code=20000, state=23505]\n     [java] FailedObject: hellojpa.Message@89e2f1\n     [java] \tat org.apache.openjpa.jdbc.sql.DBDictionary.newStoreException(DBDictionary.java:3849)\n     [java] \tat org.apache.openjpa.jdbc.sql.SQLExceptions.getStore(SQLExceptions.java:97)\n     [java] \tat org.apache.openjpa.jdbc.sql.SQLExceptions.getStore(SQLExceptions.java:67)\n     [java] \tat org.apache.openjpa.jdbc.kernel.PreparedStatementManagerImpl.flushInternal(PreparedStatementManagerImpl.java:108)\n     [java] \tat org.apache.openjpa.jdbc.kernel.PreparedStatementManagerImpl.flush(PreparedStatementManagerImpl.java:73)\n     [java] \tat org.apache.openjpa.jdbc.kernel.ConstraintUpdateManager.flush(ConstraintUpdateManager.java:543)\n     [java] \tat org.apache.openjpa.jdbc.kernel.ConstraintUpdateManager.flush(ConstraintUpdateManager.java:105)\n     [java] \tat org.apache.openjpa.jdbc.kernel.AbstractUpdateManager.flush(AbstractUpdateManager.java:89)\n     [java] \tat org.apache.openjpa.jdbc.kernel.AbstractUpdateManager.flush(AbstractUpdateManager.java:72)\n     [java] \tat org.apache.openjpa.jdbc.kernel.JDBCStoreManager.flush(JDBCStoreManager.java:514)\n     [java] \tat org.apache.openjpa.kernel.DelegatingStoreManager.flush(DelegatingStoreManager.java:130)\n     [java] \t... 8 more\n     [java] Caused by: org.apache.openjpa.lib.jdbc.ReportingSQLException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'SQL071203035857400' defined on 'MESSAGE'. {prepstmnt 28409161 INSERT INTO Message (message, created, id) VALUES (?, ?, ?) [params=(String) Hello Persistence!, (Timestamp) 2007-12-03 15:59:24.663, (long) 1196715564663]} [code=20000, state=23505]\n     [java] \tat org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator.wrap(LoggingConnectionDecorator.java:192)\n     [java] \tat org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator.access$800(LoggingConnectionDecorator.java:57)\n     [java] \tat org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator$LoggingConnection$LoggingPreparedStatement.executeUpdate(LoggingConnectionDecorator.java:858)\n     [java] \tat org.apache.openjpa.lib.jdbc.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:269)\n     [java] \tat org.apache.openjpa.jdbc.kernel.JDBCStoreManager$CancelPreparedStatement.executeUpdate(JDBCStoreManager.java:1363)\n     [java] \tat org.apache.openjpa.jdbc.kernel.PreparedStatementManagerImpl.flushInternal(PreparedStatementManagerImpl.java:97)\n     [java] \t... 15 more\n\nBUILD FAILED\nD:\\apache-openjpa-1.0.0\\examples\\build.xml:84: Java returned: 1\n\nTotal time: 6 seconds\n\n\n\n\n\n\n\n","customfield_10010":null,"timetracking":{},"customfield_12314523":null,"customfield_12314127":null,"customfield_12314522":null,"customfield_12314126":null,"customfield_12314521":null,"customfield_12314125":null,"customfield_12314520":null,"customfield_12314124":null,"attachment":[],"customfield_12312340":null,"customfield_12314123":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12314122":null,"customfield_12314121":null,"customfield_12310041":null,"customfield_12314120":null,"customfield_12314129":null,"customfield_12314524":null,"customfield_12314128":null,"summary":"OpenJPA doesn't throw standard JPA exceptions","customfield_12314130":null,"customfield_12310291":null,"customfield_12310290":null,"customfield_12314138":null,"customfield_12314137":null,"environment":"OpenJPA 1.0.0\nWindows","customfield_12314136":null,"customfield_12314135":null,"customfield_12311020":null,"customfield_12314134":null,"duedate":null,"customfield_12314132":null,"customfield_12314131":null,"comment":{"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12383824/comment/12605702","id":"12605702","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikedd","name":"mikedd","key":"mikedd","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael Dick","active":true,"timeZone":"America/Chicago"},"body":"Technically this is allowed in the JPA spec  :\n\n/**\n* Make an instance managed and persistent.\n* @param entity\n* @throws EntityExistsException if the entity already exists.\n* (The EntityExistsException may be thrown when the persist\n* operation is invoked, or the EntityExistsException or\n* another PersistenceException may be thrown at flush or\n* commit time.)\n* @throws IllegalArgumentException if not an entity\n* @throws TransactionRequiredException if invoked on a\n* container-managed entity manager of type\n* PersistenceContextType.TRANSACTION and there is\n* no transaction.\n*/\npublic void persist(Object entity);\n\nNote that we have the option of throwing an EntityExistsException or another PersistenceException (RollbackException qualifies here) at commit / flush time. \n\nI agree that it isn't very friendly though. The trick is that there isn't a universal SQLState that indicates we've received a duplicate key exception. One way to detect this condition is to maintain a list of known dup key sqlstates for each DB. Keeping the list up to date is a bit of a hassle, but it would improve the user experience.\n\nSince we're unlikely to get all the known dup key states it'd be nice to be able to update the list via the configuration. Ie : \n<property name=\"openjpa.jdbc.DBDictionary\" value=\"derby(dupKeyStates=23505,23504,23503...)\"/> <!-- except the first one these aren't accurate -->\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikedd","name":"mikedd","key":"mikedd","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Michael Dick","active":true,"timeZone":"America/Chicago"},"created":"2008-06-17T19:59:54.350+0000","updated":"2008-06-17T19:59:54.350+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12383824/comment/12606161","id":"12606161","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=ppoddar%40apache.org","name":"ppoddar@apache.org","key":"ppoddar@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Pinaki Poddar","active":true,"timeZone":"America/Los_Angeles"},"body":"Introduced a file-based configuration \"sql-error-state-codes.xml\" to narrow down the SQL exceptions. Michael is right about each database/JDBC driver throwing their own error codes on the same/similar error (e.g. DuplicateKeyException). The content of \"sql-error-state-codes.xml\" is error codes for each database we support categorized into the same subtypes of StoreException. The error codes in this file is currently gleaned from a similar file supplied in Spring framework. \n\nAlso because of *when* an exception is raised can be different than *when* user called a method (for example, an EntityExistsException can be raised at commit time and not when user called em.persist(new Entity()), the real exception is often wrapped in a javax.persistence.Rollback or generic javax.persistence.PersistenceException. \n\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=ppoddar%40apache.org","name":"ppoddar@apache.org","key":"ppoddar@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Pinaki Poddar","active":true,"timeZone":"America/Los_Angeles"},"created":"2008-06-19T00:56:45.697+0000","updated":"2008-06-19T00:56:45.697+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12383824/comment/12606162","id":"12606162","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=ppoddar%40apache.org","name":"ppoddar@apache.org","key":"ppoddar@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Pinaki Poddar","active":true,"timeZone":"America/Los_Angeles"},"body":"It may be useful for people to take a look at \"sql-error-state-codes.xml\" and help to populate it with error codes of specific databases. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=ppoddar%40apache.org","name":"ppoddar@apache.org","key":"ppoddar@apache.org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Pinaki Poddar","active":true,"timeZone":"America/Los_Angeles"},"created":"2008-06-19T00:57:09.656+0000","updated":"2008-06-19T00:57:09.656+0000"}],"maxResults":3,"total":3,"startAt":0},"customfield_12311820":"0|i0yw1z:","customfield_12314139":null}}

